# Ghost Routing Configuration for Forest Edge Theme
# This file enables custom URL structures and collections

routes:
  # Custom route for construction progress page
  /progress/:
    template: page-progress
    
  # Custom route for support/donation page
  /support/:
    template: page-support

collections:
  # Main blog posts
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-hash-internal
    
  # Construction documentation
  /construction/:
    permalink: /construction/{slug}/
    template: construction
    filter: tag:construction
    
  # Financial independence posts  
  /fi/:
    permalink: /fi/{slug}/
    template: fi
    filter: tag:financial-independence

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/